from django import forms


class PaymentSystemAuthorizeForm(forms.Form):
    PBX_SITE = forms.CharField()
    PBX_RANG = forms.CharField()
    PBX_IDENTIFIANT = forms.CharField()
    PBX_TOTAL = forms.CharField()
    PBX_DEVISE = forms.CharField()
    PBX_CMD = forms.CharField()
    PBX_PORTEUR = forms.CharField()
    PBX_RETOUR = forms.CharField()
    PBX_HASH = forms.CharField()
    PBX_TIME = forms.CharField()
    PBX_HMAC = forms.CharField()
    PBX_REFUSE = forms.CharField()
    PBX_REPONDRE_A = forms.CharField()
    PBX_EFFECTUE = forms.CharField()
    PBX_ANNULE = forms.CharField()
    PBX_ATTENTE = forms.CharField()
    PBX_LANGUE = forms.CharField()
    PBX_AUTOSEULE = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(PaymentSystemAuthorizeForm, self).__init__(*args, **kwargs)
        self.fields['PBX_SITE'].widget = forms.HiddenInput()
        self.fields['PBX_RANG'].widget = forms.HiddenInput()
        self.fields['PBX_IDENTIFIANT'].widget = forms.HiddenInput()
        self.fields['PBX_TOTAL'].widget = forms.HiddenInput()
        self.fields['PBX_DEVISE'].widget = forms.HiddenInput()
        self.fields['PBX_CMD'].widget = forms.HiddenInput()
        self.fields['PBX_PORTEUR'].widget = forms.HiddenInput()
        self.fields['PBX_RETOUR'].widget = forms.HiddenInput()
        self.fields['PBX_HASH'].widget = forms.HiddenInput()
        self.fields['PBX_TIME'].widget = forms.HiddenInput()
        self.fields['PBX_HMAC'].widget = forms.HiddenInput()
        self.fields['PBX_REFUSE'].widget = forms.HiddenInput()
        self.fields['PBX_REPONDRE_A'].widget = forms.HiddenInput()
        self.fields['PBX_EFFECTUE'].widget = forms.HiddenInput()
        self.fields['PBX_ANNULE'].widget = forms.HiddenInput()
        self.fields['PBX_ATTENTE'].widget = forms.HiddenInput()
        self.fields['PBX_LANGUE'].widget = forms.HiddenInput()
        self.fields['PBX_AUTOSEULE'].widget = forms.HiddenInput()


class PaymentSystemCaptureForm(forms.Form):
    PBX_SITE = forms.CharField()
    PBX_RANG = forms.CharField()
    PBX_IDENTIFIANT = forms.CharField()
    PBX_TOTAL = forms.CharField()
    PBX_DEVISE = forms.CharField()
    PBX_CMD = forms.CharField()
    PBX_PORTEUR = forms.CharField()
    PBX_RETOUR = forms.CharField()
    PBX_HASH = forms.CharField()
    PBX_TIME = forms.CharField()
    PBX_HMAC = forms.CharField()
    PBX_REFUSE = forms.CharField()
    PBX_REPONDRE_A = forms.CharField()
    PBX_EFFECTUE = forms.CharField()
    PBX_ANNULE = forms.CharField()
    PBX_ATTENTE = forms.CharField()
    PBX_LANGUE = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(PaymentSystemCaptureForm, self).__init__(*args, **kwargs)
        self.fields['PBX_SITE'].widget = forms.HiddenInput()
        self.fields['PBX_RANG'].widget = forms.HiddenInput()
        self.fields['PBX_IDENTIFIANT'].widget = forms.HiddenInput()
        self.fields['PBX_TOTAL'].widget = forms.HiddenInput()
        self.fields['PBX_DEVISE'].widget = forms.HiddenInput()
        self.fields['PBX_CMD'].widget = forms.HiddenInput()
        self.fields['PBX_PORTEUR'].widget = forms.HiddenInput()
        self.fields['PBX_RETOUR'].widget = forms.HiddenInput()
        self.fields['PBX_HASH'].widget = forms.HiddenInput()
        self.fields['PBX_TIME'].widget = forms.HiddenInput()
        self.fields['PBX_HMAC'].widget = forms.HiddenInput()
        self.fields['PBX_REFUSE'].widget = forms.HiddenInput()
        self.fields['PBX_REPONDRE_A'].widget = forms.HiddenInput()
        self.fields['PBX_EFFECTUE'].widget = forms.HiddenInput()
        self.fields['PBX_ANNULE'].widget = forms.HiddenInput()
        self.fields['PBX_ATTENTE'].widget = forms.HiddenInput()
        self.fields['PBX_LANGUE'].widget = forms.HiddenInput()
